stages:
  - test

test:
  variables:
    CHANGED_FILES: "git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA"
  script:
    - echo $CI_PIPELINE_SOURCE
    - echo $CHANGED_FILES
    - $CHANGED_FILES > as-is.txt
    - pwd
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - testsw