defaults:
  tags:
    - testsw

stages:
  - init
  - plan
  - apply

variables:
  CHANGED_FILES: $(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA)

init:
  stage: init
  script:
    - echo $CHANGED_FILES

plan:
  stage: plan
  script:
    - echo "THIS IS PLAN"

apply:
  stage: apply
  script:
    - echo "THIS IS APPLY"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_STATE == "merged"
