workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - merge_request
  - push_request

merge_request:
  stage: merge_request
  variables:
    CHANGED_FILES: "git diff --name-only $CI_MERGE_REQUEST_TARGET_BRANCH_SHA $CI_COMMIT_SHA"
  script:
    - echo $CI_PIPELINE_SOURCE
    - $CHANGED_FILES
    - $CHANGED_FILES > ./samsung_PoC/parsing.txt
    - pwd
    - echo "RUN TF INIT & PLAN SCRIPT"
    - cd ./samsung_PoC
    - chmod 700 script_stg.py
    - python3 script_stg.py
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  tags:
    - testsw

push_request:
  stage: push_request
  variables:
    CHANGED_FILES: "git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA"
  script:
    - echo $CI_PIPELINE_SOURCE
    - $CHANGED_FILES > ./samsung_PoC/parsing.txt
    - pwd
    - cd ./samsung_PoC
    - chmod 700 script_prd.py
    - echo "RUN TF APPLY SCRIPT"
    - python3 script_prd.py
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - testsw