stages:
  - init
  - plan
  - apply

variables:
  CHANGED_FILES: (git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA)

init:
  stage: init
  script:
    - echo "$CHANGED_FILES"
    - echo "to be parsing for init"
  tags:
    - testsw

plan:
  stage: plan
  script:
    - echo "$CHANGED_FILES"
    - echo "to be parsing for plan"
  tags:
    - testsw

apply:
  stage: apply
  script:
    - echo "THIS IS APPLY"
    - echo "to be parsing for apply"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_MERGE_REQUEST_STATE == "merged"
  tags:
    - testsw
