workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - '**/*'

stages:
  - merge_request
  - push_request

merge_request:
  stage: merge_request
  variables:
    CHANGED_FILES: "git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA"
  script:
    - echo $CI_PIPELINE_SOURCE
    - echo $CHANGED_FILES
    - $CHANGED_FILES > as-is.txt
    - pwd
  tags:
    - testsw

push_request:
  stage: push_request
  variables:
    CHANGED_FILES: "git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA"
  script:
    - echo $CI_PIPELINE_SOURCE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_APPROVED == "true"
  tags:
    - testsw