default:
  tags:
    - testsw

stages:
  - detect
  - test

detect files:
  stage: detect
  script:
    - echo $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_BRANCH
    - echo $CI_PIPELINE_SOURCE
    # - FILES=$(git diff --name-only ${CI_COMMIT_SHA} origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME})
    - git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA
    # - echo $FILES
  only:
    - merge_requests
